services:
  db:
    image: postgres:15
    hostname: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: task_management
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

networks:
  default:
    driver: bridge
    name: todo-net